export const items = [
  {
    id: 1,
    Product_type: "Guitarra Eléctrica",
    Brand: "Fender",
    Model: "Stratocaster",
    Price: 95000,
    Stock: 15,
    Category: "Guitarra",
    Img_product: <img src="/images/1000x1000/strato_negra.jpg" alt="" />,
  },
  {
    id: 2,
    Product_type: "Guitarra Eléctrica",
    Brand: "Fender",
    Model: "Telecaster",
    Price: 75000,
    Stock: 4,
    Category: "Guitarra",
    Img_product: <img src="/images/1000x1000/fender_telecaster.jpg" alt="" />,
  },
  {
    id: 3,
    Product_type: "Guitarra Eléctrica",
    Brand: "Gibson",
    Model: "Les Paul Clasic",
    Price: 110000,
    Stock: 2,
    Category: "Guitarra",
    Img_product: <img src="/images/1000x1000/gibson les paul.jpg" alt="" />,
  },
  {
    id: 4,
    Product_type: "Guitarra Eléctrica",
    Brand: "Gibson",
    Model: "SG",
    Price: 85000,
    Stock: 7,
    Category: "Guitarra",
    Img_product: <img src="/images/1000x1000/gibson-sg.jpg" alt="" />,
  },
  {
    id: 5,
    Product_type: "Guitarra Eléctrica",
    Brand: "Ibanez",
    Model: "GRx 70Qa",
    Price: 75000,
    Stock: 10,
    Category: "Guitarra",
    Img_product: (
      <img src="/images/1000x1000/ibanez-gio-grx70qa-tks.jpg" alt="" />
    ),
  },
  {
    id: 6,
    Product_type: "Guitarra Eléctrica",
    Brand: "Jackson",
    Model: "Dinky JS12",
    Price: 60000,
    Stock: 3,
    Category: "Guitarra",
    Img_product: (
      <img src="/images/1000x1000/jackson-dinky-js12-black.jpg" alt="" />
    ),
  },
];
